Repository MaibornWolff/codecharta, pull requests merged in 2018-12, with the labels that each got.

#279 Feature/273/enhance focusing nodes
  CHANGELOG.md
  visualization/app/codeCharta/codeCharta.component.html
  visualization/app/codeCharta/codeCharta.component.scss
  visualization/app/codeCharta/codeCharta.component.ts
  visualization/app/codeCharta/core/settings/settings.service.ts
  visualization/app/codeCharta/ui/blacklistPanel/blacklistPanel.component.spec.ts
  visualization/app/codeCharta/ui/blacklistPanel/blacklistPanel.component.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.actions.service.spec.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.actions.service.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.render.service.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.util.service.ts
  visualization/app/codeCharta/ui/mapTreeView/mapTreeViewLevelComponent.ts
  visualization/app/codeCharta/ui/nodeContextMenu/nodeContextMenu.component.html
  visualization/app/codeCharta/ui/nodeContextMenu/nodeContextMenu.component.ts
  visualization/app/codeCharta/ui/ribbonBar/ribbonBar.component.html
Labels: review, visualization

#290 Tech/265/Refactor revisionChooser components
  visualization/app/codeCharta/ui/revisionChooser/revisionChooser.component.html
  visualization/app/codeCharta/ui/revisionChooser/revisionChooser.component.scss
  visualization/app/codeCharta/ui/revisionChooser/revisionChooser.component.spec.ts
  visualization/app/codeCharta/ui/revisionChooser/revisionChooser.component.ts
  visualization/app/codeCharta/ui/revisionChooser/revisionChooser.ts
  visualization/app/codeCharta/ui/revisionChooser/revisionChooserFileDropDown.component.html
  visualization/app/codeCharta/ui/revisionChooser/revisionChooserFileDropDown.component.scss
Labels: review, tech

#289 Tech/287/code.map.render.service test coverage
  visualization/app/codeCharta/ui/codeMap/codeMap.render.service.spec.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.render.service.ts
Labels: review

#288 adds node context menu tests
  visualization/app/codeCharta/codeCharta.component.spec.ts
  visualization/app/codeCharta/codeCharta.component.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.component.ts
  visualization/app/codeCharta/ui/mapTreeView/mapTreeViewLevelComponent.ts
  visualization/app/codeCharta/ui/nodeContextMenu/nodeContextMenu.component.spec.ts
  visualization/app/codeCharta/ui/nodeContextMenu/nodeContextMenu.component.ts
  visualization/mocks/ng.mockhelper.ts
  visualization/package.json
Labels: review

#286 Tech/285/map tree view component test coverage
  visualization/app/codeCharta/ui/mapTreeView/mapTreeView.ts
  visualization/app/codeCharta/ui/mapTreeView/mapTreeViewLevelComponent.spec.ts
  visualization/app/codeCharta/ui/mapTreeView/mapTreeViewLevelComponent.ts
Labels: review

#294 Tech/265/add tests download service
  visualization/app/codeCharta/core/download/__snapshots__/download.service.spec.ts.snap
  visualization/app/codeCharta/core/download/download.service.spec.ts
  visualization/app/codeCharta/core/download/download.service.ts
  visualization/mocks/dateMock.helper.ts
Labels: review, tech
