Repository MaibornWolff/codecharta, pull requests merged in 2018-11, with the labels that each got.

#260 PR for "Buildings in the delta view are not colored correctly #253"
  CHANGELOG.md
  visualization/app/codeCharta/core/treemap/treemap.util.spec.ts
  visualization/app/codeCharta/core/treemap/treemap.util.ts
Labels: review

#261 Feature/254/make deleted buildings visible
  CHANGELOG.md
  visualization/app/codeCharta/core/data/data.deltaCalculator.service.ts
  visualization/app/codeCharta/core/data/data.service.spec.ts
  visualization/app/codeCharta/core/data/data.service.ts
  visualization/app/codeCharta/core/treemap/treemap.service.ts
  visualization/app/codeCharta/core/treemap/treemap.spec.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.render.service.ts
Labels: review

#267 #236 #240 adds an automatic line break detection
  analysis/import/CSVImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/csv/CSVProjectBuilder.kt
  analysis/import/CSVImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/csv/CSVProjectBuilderTest.kt
  analysis/import/UnderstandImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/understand/UnderstandProjectBuilder.kt
  analysis/import/UnderstandImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/understand/UnderstandProjectBuilderTest.kt
  analysis/import/UnderstandImporter/src/test/resources/understand_lf.csv
Labels: review

#272 Bug/271/fix hiding nodes in treeview blacklist
  CHANGELOG.md
  visualization/app/codeCharta/ui/codeMap/codeMap.render.service.ts
  visualization/app/codeCharta/ui/nodeContextMenu/nodeContextMenu.component.html
Labels: bug, review, visualization

#269 Feature/238/fix the drawing distance
  visualization/app/codeCharta/ui/codeMap/threeViewer/threeCameraService.ts
Labels: review

#278 Update Readme screenshot and update invert color checkbox
  screenshot.png
  visualization/app/codeCharta/ui/ribbonBar/ribbonBar.component.html
  visualization/app/codeCharta/ui/ribbonBar/ribbonBar.component.scss
Labels: documentation, review, visualization

#241 Extend understandimporter by class metrics
  analysis/build.gradle
  analysis/import/CSVImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/csv/CSVHeader.kt
  analysis/import/CSVImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/csv/CSVProjectBuilder.kt
  analysis/import/CSVImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/csv/CSVRow.kt
  analysis/import/CSVImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/csv/SourceMonitorImporter.kt
  analysis/import/CSVImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/csv/CSVProjectBuilderTest.kt
  analysis/import/CSVImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/csv/CSVRowTest.kt
  analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/SonarComponentProjectBuilder.kt
  analysis/import/SonarImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/sonar/SonarComponentProjectBuilderTest.kt
  analysis/import/UnderstandImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/understand/HelperFunctions.kt
  analysis/import/UnderstandImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/understand/UnderstandCSVHeader.kt
  analysis/import/UnderstandImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/understand/UnderstandCSVRow.kt
  analysis/import/UnderstandImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/understand/UnderstandImporter.kt
  analysis/import/UnderstandImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/understand/UnderstandProjectBuilder.kt
  analysis/import/UnderstandImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/understand/CSVRowTest.kt
  analysis/import/UnderstandImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/understand/HelperFunctionsTest.kt
  analysis/import/UnderstandImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/understand/UnderstandCSVHeaderTest.kt
  analysis/import/UnderstandImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/understand/UnderstandCSVRowTest.kt
  analysis/import/UnderstandImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/understand/UnderstandProjectBuilderTest.kt
  analysis/import/UnderstandImporter/src/test/resources/understand_lf.csv
  analysis/model/src/main/kotlin/de/maibornwolff/codecharta/attributeTypes/AttributeTypes.kt
  analysis/model/src/main/kotlin/de/maibornwolff/codecharta/model/MutableNode.kt
  analysis/model/src/main/kotlin/de/maibornwolff/codecharta/model/Node.kt
  analysis/model/src/main/kotlin/de/maibornwolff/codecharta/model/NodeInserter.kt
  analysis/model/src/main/kotlin/de/maibornwolff/codecharta/model/NodeMaxAttributeMerger.kt
  analysis/model/src/main/kotlin/de/maibornwolff/codecharta/model/Project.kt
  analysis/model/src/main/kotlin/de/maibornwolff/codecharta/model/ProjectBuilder.kt
  analysis/model/src/test/kotlin/de/maibornwolff/codecharta/model/NodeMergerTest.kt
  analysis/model/src/test/kotlin/de/maibornwolff/codecharta/model/ProjectBuilderTest.kt
Labels: review

#282 Adds plop code generation support
  CHANGELOG.md
  visualization/README.md
  visualization/app/codeCharta/core/core.module.ts
  visualization/app/codeCharta/ui/ui.ts
  visualization/package-lock.json
  visualization/package.json
  visualization/plop-templates/component.html.hbs
  visualization/plop-templates/component.scss.hbs
  visualization/plop-templates/component.spec.ts.hbs
  visualization/plop-templates/component.ts.hbs
  visualization/plop-templates/core.module.ts.hbs
  visualization/plop-templates/e2e.ts.hbs
  visualization/plop-templates/service.spec.ts.hbs
  visualization/plop-templates/service.ts.hbs
  visualization/plop-templates/ui.module.ts.hbs
  visualization/plopfile.js
Labels: review

#283 Tech/265/add tests legend panel
  visualization/app/codeCharta/ui/legendPanel/legendPanel.component.html
  visualization/app/codeCharta/ui/legendPanel/legendPanel.component.scss
  visualization/app/codeCharta/ui/legendPanel/legendPanel.component.spec.ts
  visualization/app/codeCharta/ui/legendPanel/legendPanel.component.ts
  visualization/app/codeCharta/ui/legendPanel/legendPanel.ts
  visualization/app/codeCharta/ui/legendPanel/legendPanelController.spec.js
Labels: review, tech

#284 Add test files for blacklistPanel #265
  visualization/app/codeCharta/ui/blacklistPanel/blacklistPanel.component.spec.ts
Labels: review, tech
