Repository MaibornWolff/codecharta, pull requests merged in 2018-10, with the labels that each got.

#242 Bug220 show deltas on url loading
  CHANGELOG.md
  visualization/MANUAL_TESTING.md
  visualization/app/codeCharta/core/aggregate/aggregate.module.ts
  visualization/app/codeCharta/core/core.module.ts
  visualization/app/codeCharta/core/multipleFile/multipleFile.module.ts
  visualization/app/codeCharta/core/multipleFile/multipleFile.service.spec.ts
  visualization/app/codeCharta/core/multipleFile/multipleFile.service.ts
  visualization/app/codeCharta/core/scenario/scenario.data.ts
  visualization/app/codeCharta/core/scenario/scenario.spec.ts
  visualization/app/codeCharta/core/scenario/scenarios.json
  visualization/app/codeCharta/core/settings/settings.service.ts
  visualization/app/codeCharta/core/settings/settings.spec.ts
  visualization/app/codeCharta/ui/aggregateSettingsPanel/aggregateSettingsPanel.component.scss
  visualization/app/codeCharta/ui/aggregateSettingsPanel/aggregateSettingsPanel.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.render.service.ts
  visualization/app/codeCharta/ui/colorSettingsPanel/colorSettingsPanel.component.html
  visualization/app/codeCharta/ui/colorSettingsPanel/colorSettingsPanel.component.ts
  visualization/app/codeCharta/ui/colorSettingsPanel/colorSettingsPanel.controller.spec.ts
  visualization/app/codeCharta/ui/detailPanel/detailPanelComponent.ts
  visualization/app/codeCharta/ui/displaySettingsPanel/displaySettingsPanel.component.ts
  visualization/app/codeCharta/ui/displaySettingsPanel/displaySettingsPanel.controller.spec.ts
  visualization/app/codeCharta/ui/experimentalSettingsPanel/experimentalSettingsPanel.ts
  visualization/app/codeCharta/ui/legendPanel/legendPanelComponent.ts
  visualization/app/codeCharta/ui/multipleFilePanel/multipleFilePanel.component.html
  visualization/app/codeCharta/ui/multipleFilePanel/multipleFilePanel.component.scss
  visualization/app/codeCharta/ui/multipleFilePanel/multipleFilePanel.ts
  visualization/app/codeCharta/ui/multipleFilePanel/multipleFilePanelComponent.ts
  visualization/app/codeCharta/ui/optionsPanel/optionsPanel.ts
  visualization/app/codeCharta/ui/resetSettingsButton/resetSettingsButton.controller.spec.ts
  visualization/app/codeCharta/ui/revisionChooser/revisionChooser.html
  visualization/app/codeCharta/ui/revisionChooser/revisionChooserComponent.ts
  visualization/app/codeCharta/ui/revisionChooser/revisionChooserFileDropDown.html
  visualization/app/codeCharta/ui/ribbonBar/ribbonBar.component.html
  visualization/app/codeCharta/ui/weblinksPanel/weblinksPanel.ts
Labels: review

#250 Feature/205/exlude items in new file
  CHANGELOG.md
  analysis/tools/ValidationTool/src/main/resources/cc.json
  visualization/app/codeCharta/codeCharta.component.scss
  visualization/app/codeCharta/core/core.module.ts
  visualization/app/codeCharta/core/data/data.loading.service.ts
  visualization/app/codeCharta/core/data/data.validator.service.spec.ts
  visualization/app/codeCharta/core/data/data.validator.service.ts
  visualization/app/codeCharta/core/data/model/CodeMap.ts
  visualization/app/codeCharta/core/data/schema.json
  visualization/app/codeCharta/core/download/download.module.ts
  visualization/app/codeCharta/core/download/download.service.ts
  visualization/app/codeCharta/core/scenario/scenario.data.ts
  visualization/app/codeCharta/core/scenario/scenario.service.ts
  visualization/app/codeCharta/core/scenario/scenario.spec.ts
  visualization/app/codeCharta/core/scenario/scenarios.json
  visualization/app/codeCharta/core/settings/settings.service.ts
  visualization/app/codeCharta/core/treemap/__snapshots__/treemap.spec.ts.snap
  visualization/app/codeCharta/core/treemap/treemap.service.ts
  visualization/app/codeCharta/core/treemap/treemap.spec.ts
  visualization/app/codeCharta/core/treemap/treemap.util.spec.ts
  visualization/app/codeCharta/ui/blacklistPanel/blacklistPanel.component.html
  visualization/app/codeCharta/ui/blacklistPanel/blacklistPanel.component.scss
  visualization/app/codeCharta/ui/blacklistPanel/blacklistPanel.component.ts
  visualization/app/codeCharta/ui/blacklistPanel/blacklistPanel.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.actions.service.spec.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.actions.service.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.component.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.render.service.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.util.service.ts
  visualization/app/codeCharta/ui/legendPanel/legendPanel.scss
  visualization/app/codeCharta/ui/mapTreeView/mapTreeViewComponent.ts
  visualization/app/codeCharta/ui/mapTreeView/mapTreeViewLevel.html
  visualization/app/codeCharta/ui/mapTreeView/mapTreeViewLevelComponent.ts
  visualization/app/codeCharta/ui/multipleFilePanel/multipleFilePanel.component.html
  visualization/app/codeCharta/ui/multipleFilePanel/multipleFilePanel.ts
  visualization/app/codeCharta/ui/nodeContextMenu/nodeContextMenu.component.html
  visualization/app/codeCharta/ui/nodeContextMenu/nodeContextMenu.component.scss
  visualization/app/codeCharta/ui/nodeContextMenu/nodeContextMenu.component.ts
  visualization/app/codeCharta/ui/resetSettingsButton/resetSettingsButton.component.html
  visualization/app/codeCharta/ui/resetSettingsButton/resetSettingsButton.component.scss
  visualization/app/codeCharta/ui/revisionChooser/revisionChooserFileDropDown.html
  visualization/app/codeCharta/ui/revisionChooser/revisionChooserFileDropDown.scss
  visualization/app/codeCharta/ui/ribbonBar/ribbonBar.component.html
  visualization/app/codeCharta/ui/ribbonBar/ribbonBar.component.scss
  visualization/app/codeCharta/ui/ribbonBar/ribbonBar.component.ts
  visualization/app/codeCharta/ui/ribbonBar/ribbonBar.module.ts
  visualization/app/codeCharta/ui/settingsPanel/settingsPanel.html
  visualization/app/codeCharta/ui/sidenav/sidenav.component.html
  visualization/app/codeCharta/ui/sidenav/sidenav.component.scss
  visualization/app/codeCharta/ui/sidenav/sidenav.component.ts
  visualization/app/codeCharta/ui/ui.ts
  visualization/package-lock.json
  visualization/package.json
Labels: cc.json, review, save, visualization

#248 Adds Integraton for Jasome
  CHANGELOG.md
  analysis/README.md
  analysis/import/JasomeImporter/README.md
  analysis/import/JasomeImporter/build.gradle
  analysis/import/JasomeImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/jasome/JasomeDeserializer.kt
  analysis/import/JasomeImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/jasome/JasomeImporter.kt
  analysis/import/JasomeImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/jasome/JasomeProjectBuilder.kt
  analysis/import/JasomeImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/jasome/model/Class.kt
  analysis/import/JasomeImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/jasome/model/Metric.kt
  analysis/import/JasomeImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/jasome/model/Package.kt
  analysis/import/JasomeImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/jasome/model/Project.kt
  analysis/import/JasomeImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/jasome/JasomeDeserializerTest.kt
  analysis/import/JasomeImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/jasome/JasomeProjectBuilderTest.kt
  analysis/import/JasomeImporter/src/test/resources/jasome.xml
  analysis/model/src/main/kotlin/de/maibornwolff/codecharta/model/Path.kt
  analysis/settings.gradle
  analysis/test/data/codecharta/jasome.xml
  analysis/test/golden_test.sh
  analysis/tools/ccsh/build.gradle
  analysis/tools/ccsh/src/main/kotlin/de/maibornwolff/codecharta/tools/ccsh/Ccsh.kt
Labels: review

#257 Publish codecharta-visualization in Docker Hub
  .travis.yml
  CHANGELOG.md
  README.md
  VERSION_BUMPING.md
  analysis/build.gradle
  analysis/gradle.properties
  analysis/import/UnderstandImporter/build.gradle
  analysis/script/sonar-publish.sh
  analysis/sonar-project.properties
  visualization/Dockerfile
  visualization/package-lock.json
  visualization/script/docker-publish.sh
  visualization/script/travis-build.sh
Labels: review

#256 Bug/255/reset buttons
  CHANGELOG.md
  visualization/app/codeCharta/ui/colorSettingsPanel/colorSettingsPanel.component.html
  visualization/app/codeCharta/ui/colorSettingsPanel/colorSettingsPanel.component.ts
  visualization/app/codeCharta/ui/colorSettingsPanel/colorSettingsPanel.controller.spec.ts
  visualization/app/codeCharta/ui/ribbonBar/ribbonBar.component.html
  visualization/app/codeCharta/ui/ribbonBar/ribbonBar.component.ts
Labels: bug, review, visualization
