Repository MaibornWolff/codecharta, pull requests merged in 2019-04, with the labels that each got.

#467 Tech/dependabot javascript
  CHANGELOG.md
  visualization/package-lock.json
  visualization/package.json
Labels: dependencies, javascript

#468 Tech/408/analysis code format
  analysis/README.md
  analysis/intellij-resources/codestyle.xml
Labels: review, tech

#481 Fix bug that trailing slash would crash sonar importer #356
  CHANGELOG.md
  analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/SonarImporterMain.kt
  analysis/import/SonarImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/sonar/SonarImporterMainTest.kt
Labels: analysis, bug, review

#487 Tech/471/settings mapcolors
  visualization/app/codeCharta/codeCharta.model.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.arrow.service.spec.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.arrow.service.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.label.service.spec.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.label.service.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.render.service.ts
  visualization/app/codeCharta/ui/codeMap/rendering/codeMapBuilding.ts
  visualization/app/codeCharta/ui/codeMap/rendering/codeMapMesh.ts
  visualization/app/codeCharta/ui/codeMap/rendering/geometryGenerator.ts
  visualization/app/codeCharta/ui/codeMap/rendering/node.ts
  visualization/app/codeCharta/ui/codeMap/rendering/renderSettings.ts
  visualization/app/codeCharta/ui/codeMap/rendering/rendering.spec.ts
  visualization/app/codeCharta/ui/codeMap/rendering/renderingUtil.ts
  visualization/app/codeCharta/ui/codeMap/treemap/treemap.service.spec.ts
  visualization/app/codeCharta/ui/codeMap/treemap/treemap.service.ts
  visualization/app/codeCharta/ui/codeMap/treemap/treemap.util.ts
  visualization/app/codeCharta/ui/detailPanel/detailPanel.component.ts
  visualization/app/codeCharta/ui/legendPanel/legendPanel.component.ts
  visualization/app/codeCharta/ui/mapTreeView/mapTreeView.level.component.spec.ts
  visualization/app/codeCharta/ui/nodeContextMenu/nodeContextMenu.component.ts
  visualization/app/codeCharta/ui/rangeSlider/rangeSlider.component.ts
  visualization/app/codeCharta/util/dataMocks.ts
Labels: review, tech

#488 Remove unused metric tooltip component
  visualization/app/codeCharta/assets/tooltips.json
  visualization/app/codeCharta/ui/tooltip/tooltip.module.ts
  visualization/app/codeCharta/ui/tooltip/tooltip.service.spec.ts
  visualization/app/codeCharta/ui/tooltip/tooltip.service.ts
  visualization/app/codeCharta/ui/ui.ts
Labels: review, tech

#489 Refactor treemap.service
  visualization/app/codeCharta/ui/codeMap/codeMap.render.service.ts
  visualization/app/codeCharta/util/__snapshots__/treeMapGenerator.spec.ts.snap
  visualization/app/codeCharta/util/__snapshots__/treeMapHelper.spec.ts.snap
  visualization/app/codeCharta/util/treeMapGenerator.spec.ts
  visualization/app/codeCharta/util/treeMapGenerator.ts
  visualization/app/codeCharta/util/treeMapHelper.spec.ts
  visualization/app/codeCharta/util/treeMapHelper.ts
Labels: review, tech

#486 Feature/346/performance
  CHANGELOG.md
  visualization/app/codeCharta/codeCharta.component.ts
  visualization/app/codeCharta/state/fileState.service.ts
  visualization/app/codeCharta/state/settings.service.spec.ts
  visualization/app/codeCharta/state/settings.service.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.preRender.service.ts
  visualization/app/codeCharta/ui/ribbonBar/ribbonBar.component.html
  visualization/app/codeCharta/ui/ribbonBar/ribbonBar.component.scss
  visualization/app/codeCharta/ui/ribbonBar/ribbonBar.component.ts
Labels: review, visualization
