Repository MaibornWolff/codecharta, pull requests merged in 2020-08, with the labels that each got.

#1140 Docs/986/move wiki to gh pages
  CHANGELOG.md
  gh-pages/_docs/01-03-installation.md
  gh-pages/_docs/07-01-new-to-code.md
  gh-pages/_docs/10-01-license.md
  gh-pages/_posts/dev-guide/2020-07-31-e2e-testing-with-puppeteer.md
  gh-pages/_posts/dev-guide/2020-08-04-make-a-release.md
  gh-pages/_posts/how-to/2019-06-28-analyze_codecharta_with_sonarqube_and_git_svn.md
  gh-pages/assets/images/docs/reference/loading-a-new-file-flow.png
  gh-pages/assets/images/docs/reference/redux-flow.png
Labels: documentation

#1138 Fix/1103/support tokei 12
  CHANGELOG.md
  analysis/filter/StructureModifier/build.gradle
  analysis/import/CrococosmoImporter/build.gradle
  analysis/import/SCMLogParser/build.gradle
  analysis/import/SonarImporter/build.gradle
  analysis/import/SourceCodeParser/build.gradle
  analysis/import/TokeiImporter/build.gradle
  analysis/import/TokeiImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/tokeiimporter/AnalysisObject.kt
  analysis/import/TokeiImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/tokeiimporter/TokeiImporter.kt
  analysis/import/TokeiImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/tokeiimporter/analysisObject/AnalysisObject.kt
  analysis/import/TokeiImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/tokeiimporter/analysisObject/AnalysisObjectTwelve.kt
  analysis/import/TokeiImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/tokeiimporter/strategy/ImporterStrategy.kt
  analysis/import/TokeiImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/tokeiimporter/strategy/TokeiInnerStrategy.kt
  analysis/import/TokeiImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/tokeiimporter/strategy/TokeiTwelveStrategy.kt
  analysis/import/TokeiImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/tokeiimporter/TokeiImporterTest.kt
  analysis/import/TokeiImporter/src/test/resources/tokei_without_inner.json
  analysis/parser/RawTextParser/build.gradle
  analysis/parser/RawTextParser/src/test/kotlin/de/maibornwolff/codecharta/indentationlevelparser/RawTextParserTest.kt
  analysis/parser/RawTextParser/src/test/resources/cc_projects/project_4.cc.json
Labels: bug, pr-analysis

#1146 Fix/sonar does not trigger on main
  .travis.yml
Labels: tech

#1145 Tech/improve breaking change information
  CHANGELOG.md
  analysis/README.md
Labels: documentation

#1149 Tech/gh-pages-release-post-not-formatted-correctly
  script/make_release.py
Labels: tech

#1148 Tech/demo use new sonarcloud projects
  analysis/script/travis-build.sh
  gh-pages/_posts/how-to/2019-06-28-analyze_codecharta_with_sonarqube_and_git_svn.md
  script/build_gh_pages.sh
Labels: tech

#1150 Tech/fix e2e test race condition
  visualization/app/codeCharta/ui/dialog/dialog.error.po.ts
  visualization/app/codeCharta/ui/fileChooser/fileChooser.e2e.ts
Labels: priority:high, tech

#1151 Tech/run-commit-hooks-on-release
  script/make_release.py
Labels: tech

#1153 Format project
  CHANGELOG.md
  visualization/package-lock.json
  visualization/package.json
Labels: tech

#1156 Tech/eslint-enable-no-vars-parameter
  visualization/.eslintrc.js
  visualization/app/codeCharta/state/edgeMetricData.service.spec.ts
  visualization/app/codeCharta/state/edgeMetricData.service.ts
  visualization/app/codeCharta/state/metric.service.spec.ts
  visualization/app/codeCharta/state/metric.service.ts
  visualization/app/codeCharta/state/store/appSettings/isAttributeSideBarVisible/isAttributeSideBarVisible.service.spec.ts
  visualization/app/codeCharta/state/store/appSettings/isAttributeSideBarVisible/isAttributeSideBarVisible.service.ts
  visualization/app/codeCharta/state/store/dynamicSettings/colorRange/colorRange.service.spec.ts
  visualization/app/codeCharta/state/store/dynamicSettings/colorRange/colorRange.service.ts
  visualization/app/codeCharta/state/store/dynamicSettings/focusedNodePath/focusedNodePath.service.spec.ts
  visualization/app/codeCharta/state/store/dynamicSettings/focusedNodePath/focusedNodePath.service.ts
  visualization/app/codeCharta/state/store/dynamicSettings/margin/margin.service.ts
  visualization/app/codeCharta/state/store/dynamicSettings/searchPattern/searchPattern.service.spec.ts
  visualization/app/codeCharta/state/store/dynamicSettings/searchPattern/searchPattern.service.ts
  visualization/app/codeCharta/ui/areaSettingsPanel/areaSettingsPanel.component.spec.ts
  visualization/app/codeCharta/ui/areaSettingsPanel/areaSettingsPanel.component.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.label.service.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.mouseEvent.service.spec.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.mouseEvent.service.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.preRender.service.spec.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.preRender.service.ts
  visualization/app/codeCharta/ui/codeMap/threeViewer/threeCameraService.spec.ts
  visualization/app/codeCharta/ui/codeMap/threeViewer/threeCameraService.ts
  visualization/app/codeCharta/ui/codeMap/threeViewer/threeOrbitControlsService.spec.ts
  visualization/app/codeCharta/ui/codeMap/threeViewer/threeOrbitControlsService.ts
  visualization/app/codeCharta/ui/codeMap/threeViewer/threeSceneService.spec.ts
  visualization/app/codeCharta/ui/codeMap/threeViewer/threeSceneService.ts
  visualization/app/codeCharta/ui/legendPanel/legendPanel.component.spec.ts
  visualization/app/codeCharta/ui/legendPanel/legendPanel.component.ts
  visualization/app/codeCharta/ui/mapTreeView/mapTreeView.component.spec.ts
  visualization/app/codeCharta/ui/mapTreeView/mapTreeView.component.ts
  visualization/app/codeCharta/ui/mapTreeView/mapTreeView.level.component.ts
  visualization/app/codeCharta/ui/matchingFilesCounter/matchingFilesCounter.component.ts
  visualization/app/codeCharta/ui/metricDeltaSelected/metricDeltaSelected.component.ts
  visualization/app/codeCharta/ui/nodeContextMenu/nodeContextMenu.component.spec.ts
  visualization/app/codeCharta/ui/nodeContextMenu/nodeContextMenu.component.ts
  visualization/app/codeCharta/ui/rangeSlider/rangeSlider.component.spec.ts
  visualization/app/codeCharta/ui/rangeSlider/rangeSlider.component.ts
  visualization/app/codeCharta/ui/scenarioDropDown/scenarioDropDown.component.spec.ts
  visualization/app/codeCharta/ui/scenarioDropDown/scenarioDropDown.component.ts
  visualization/app/codeCharta/ui/searchBar/searchBar.component.spec.ts
  visualization/app/codeCharta/ui/searchBar/searchBar.component.ts
  visualization/app/codeCharta/ui/toolBar/toolBar.component.spec.ts
  visualization/app/codeCharta/ui/toolBar/toolBar.component.ts
  visualization/app/codeCharta/ui/unfocusButton/unfocusButton.component.spec.ts
  visualization/app/codeCharta/ui/unfocusButton/unfocusButton.component.ts
Labels: tech

#1143 Fix/1027/dont show node context menu when mouse moved
  CHANGELOG.md
  visualization/app/codeCharta/ui/codeMap/codeMap.mouseEvent.service.spec.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.mouseEvent.service.ts
Labels: bug, pr-visualization

#1166 docs/analysis-test-add-sh-to-path
  CHANGELOG.md
  gh-pages/_docs/07-01-new-to-code.md
Labels: difficulty:low, documentation, pr-analysis

#1169 fix/1161/solve-unclosing-node-options
  visualization/app/codeCharta/ui/codeMap/codeMap.mouseEvent.service.spec.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.mouseEvent.service.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.po.ts
  visualization/app/codeCharta/ui/nodeContextMenu/nodeContextMenu.e2e.ts
  visualization/app/codeCharta/ui/nodeContextMenu/nodeContextMenu.po.ts
Labels: help wanted, pr-visualization

#1164 Feature/1042/cursor indicator for move and rotate
  CHANGELOG.md
  visualization/app/codeCharta/ui/codeMap/codeMap.mouseEvent.service.spec.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.mouseEvent.service.ts
  visualization/app/codeCharta/ui/viewCube/viewCube.mouseEvents.service.ts
Labels: pr-visualization

#1171 Tech/upgrade-pretty-quick
  package-lock.json
  package.json
Labels: dependencies, tech

#1172 tech/fix-cve-issue-activesupport-gh-pages
  gh-pages/Gemfile
  gh-pages/Gemfile.lock
Labels: dependencies, documentation, security, tech
