Repository MaibornWolff/codecharta, pull requests merged in 2020-02, with the labels that each got.

#855 Tech/Fix plop generator
  visualization/plopfile.js
Labels: bug, tech

#831 Tech/refactor resetting file settings
  visualization/app/codeCharta/state/store.service.spec.ts
  visualization/app/codeCharta/state/store.service.ts
  visualization/app/codeCharta/state/store/dynamicSettings/dynamicSettings.splitter.ts
  visualization/app/codeCharta/state/store/fileSettings/attributeTypes/attributeTypes.merger.spec.ts
  visualization/app/codeCharta/state/store/fileSettings/attributeTypes/attributeTypes.merger.ts
  visualization/app/codeCharta/state/store/fileSettings/attributeTypes/attributeTypes.service.spec.ts
  visualization/app/codeCharta/state/store/fileSettings/attributeTypes/attributeTypes.service.ts
  visualization/app/codeCharta/state/store/fileSettings/blacklist/__snapshots__/blacklist.merger.spec.ts.snap
  visualization/app/codeCharta/state/store/fileSettings/blacklist/blacklist.merger.spec.ts
  visualization/app/codeCharta/state/store/fileSettings/blacklist/blacklist.merger.ts
  visualization/app/codeCharta/state/store/fileSettings/blacklist/blacklist.service.spec.ts
  visualization/app/codeCharta/state/store/fileSettings/blacklist/blacklist.service.ts
  visualization/app/codeCharta/state/store/fileSettings/edges/__snapshots__/edges.merger.spec.ts.snap
  visualization/app/codeCharta/state/store/fileSettings/edges/edges.merger.spec.ts
  visualization/app/codeCharta/state/store/fileSettings/edges/edges.merger.ts
  visualization/app/codeCharta/state/store/fileSettings/edges/edges.service.spec.ts
  visualization/app/codeCharta/state/store/fileSettings/edges/edges.service.ts
  visualization/app/codeCharta/state/store/fileSettings/markedPackages/__snapshots__/markedPackages.merger.spec.ts.snap
  visualization/app/codeCharta/state/store/fileSettings/markedPackages/markedPackages.merger.spec.ts
  visualization/app/codeCharta/state/store/fileSettings/markedPackages/markedPackages.merger.ts
  visualization/app/codeCharta/state/store/fileSettings/markedPackages/markedPackages.service.spec.ts
  visualization/app/codeCharta/state/store/fileSettings/markedPackages/markedPackages.service.ts
  visualization/app/codeCharta/util/__snapshots__/settingsMerger.spec.ts.snap
  visualization/app/codeCharta/util/aggregationGenerator.ts
  visualization/app/codeCharta/util/nodePathHelper.ts
  visualization/app/codeCharta/util/settingsMerger.spec.ts
  visualization/app/codeCharta/util/settingsMerger.ts
Labels: tech

#864 Tech/node type as enum
  visualization/app/codeCharta/codeCharta.model.ts
  visualization/app/codeCharta/codeCharta.service.spec.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.component.ts
  visualization/app/codeCharta/ui/fileExtensionBar/fileExtensionBar.component.spec.ts
  visualization/app/codeCharta/ui/mapTreeView/mapTreeView.level.component.spec.ts
  visualization/app/codeCharta/ui/nodeContextMenu/nodeContextMenu.component.spec.ts
  visualization/app/codeCharta/util/aggregationGenerator.spec.ts
  visualization/app/codeCharta/util/aggregationGenerator.ts
  visualization/app/codeCharta/util/codeMapHelper.spec.ts
  visualization/app/codeCharta/util/codeMapHelper.ts
  visualization/app/codeCharta/util/dataMocks.ts
  visualization/app/codeCharta/util/deltaGenerator.spec.ts
  visualization/app/codeCharta/util/fileDownloader.ts
  visualization/app/codeCharta/util/fileExtensionCalculator.spec.ts
  visualization/app/codeCharta/util/fileValidator.spec.ts
  visualization/app/codeCharta/util/mapBuilder.spec.ts
  visualization/app/codeCharta/util/mapBuilder.ts
  visualization/app/codeCharta/util/nodeDecorator.spec.ts
  visualization/app/codeCharta/util/treeMapHelper.spec.ts
Labels: tech

#862 Bug/857/Loading Gif not displayed when preparing to render a new map
  CHANGELOG.md
  visualization/app/codeCharta/state/store.service.spec.ts
  visualization/app/codeCharta/state/store.service.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.preRender.service.spec.ts
  visualization/app/codeCharta/ui/codeMap/codeMap.preRender.service.ts
  visualization/package-lock.json
  visualization/tsconfig.webpack.json
Labels: bug, pr-visualization
