Repository MaibornWolff/codecharta, pull requests merged in 2021-05, with the labels that each got.

#1982 Fix/1952/UI elements should not change their size when clicked upon
  CHANGELOG.md
  package-lock.json
  visualization/app/codeCharta/ui/areaSettingsPanel/areaSettingsPanel.component.html
  visualization/app/codeCharta/ui/areaSettingsPanel/areaSettingsPanel.component.scss
  visualization/app/codeCharta/ui/colorSettingsPanel/colorSettingsPanel.component.html
  visualization/app/codeCharta/ui/colorSettingsPanel/colorSettingsPanel.component.scss
  visualization/app/codeCharta/ui/customColorPicker/storeColorPicker/storeColorPicker.component.scss
  visualization/app/codeCharta/ui/edgeSettingsPanel/edgeSettingsPanel.component.html
  visualization/app/codeCharta/ui/edgeSettingsPanel/edgeSettingsPanel.component.scss
  visualization/app/codeCharta/ui/heightSettingsPanel/heightSettingsPanel.component.html
  visualization/app/codeCharta/ui/heightSettingsPanel/heightSettingsPanel.component.scss
  visualization/app/codeCharta/ui/metricChooser/metricChooser.po.ts
  visualization/app/codeCharta/ui/metricValueHovered/metricValueHovered.area.component.html
  visualization/app/codeCharta/ui/rangeSlider/rangeSlider.component.scss
  visualization/app/codeCharta/ui/resetSettingsButton/resetSettingsButton.component.scss
  visualization/app/codeCharta/ui/ribbonBar/ribbonBar.component.html
  visualization/app/codeCharta/ui/ribbonBar/ribbonBar.component.scss
  visualization/app/codeCharta/ui/ribbonBar/ribbonBar.e2e.ts
  visualization/app/codeCharta/ui/ribbonBar/ribbonBar.po.ts
Labels: UX / UI

#2014 fix: deprecated url parameter for sonarqube version lower than 6.6
  CHANGELOG.md
  analysis/import/SonarImporter/build.gradle
  analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/SonarImporterMain.kt
  analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/dataaccess/SonarMeasuresAPIDatasource.kt
  analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/dataaccess/SonarVersionAPIDatasource.kt
  analysis/import/SonarImporter/src/main/kotlin/de/maibornwolff/codecharta/importer/sonar/model/Version.kt
  analysis/import/SonarImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/sonar/SonarImporterMainTest.kt
  analysis/import/SonarImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/sonar/dataaccess/SonarMeasuresAPIDatasourceIntegrationTest.kt
  analysis/import/SonarImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/sonar/dataaccess/SonarVersionAPIDatasourceIntegrationTest.kt
  analysis/import/SonarImporter/src/test/kotlin/de/maibornwolff/codecharta/importer/sonar/model/VersionTest.kt
Labels: pr-analysis

#1897 Fix/1592/slider not initialized correctly
  CHANGELOG.md
  visualization/app/codeCharta/ui/rangeSlider/rangeSlider.component.spec.ts
  visualization/app/codeCharta/ui/rangeSlider/rangeSlider.component.ts
Labels: UX / UI, bug, javascript
