Repository MaibornWolff/codecharta, pull requests merged in 2021-04, with the labels that each got.

#1923 Deps/update all dependencies
  .prettierignore
  Pipfile.lock
  package-lock.json
  package.json
  visualization/.gitignore
  visualization/app/codeCharta/resources/fileStorage/.gitkeep
  visualization/app/codeCharta/resources/fileStorage/usageData/.gitkeep
  visualization/app/codeCharta/resources/fixed-folders/example.json
  visualization/app/codeCharta/resources/fixed-folders/fixed-folders-example.ts
  visualization/app/codeCharta/resources/sample1_with_api_warning.cc.json
  visualization/app/codeCharta/resources/sample1_with_different_edges.cc.json
  visualization/app/codeCharta/resources/sample1_with_lower_minor_api.cc.json
  visualization/app/codeCharta/ui/dialog/dialog.globalSettings.e2e.ts
  visualization/app/codeCharta/ui/edgeChooser/edgeChooser.e2e.ts
  visualization/app/codeCharta/ui/fileChooser/fileChooser.e2e.ts
  visualization/app/codeCharta/ui/legendPanel/legendPanel.e2e.ts
  visualization/app/codeCharta/util/algorithm/treeMapLayout/treeMapGenerator.spec.ts
  visualization/app/codeCharta/util/codeChartaStorage.ts
  visualization/app/codeCharta/util/fileValidator.spec.ts
  visualization/conf/webpack.config.js
  visualization/conf/webpack.loaders.js
  visualization/package-lock.json
  visualization/package.json
Labels: dependencies, javascript

#1912 Removes unused whitespaces in the searchbar
  CHANGELOG.md
  visualization/app/codeCharta/codeCharta.component.scss
  visualization/app/codeCharta/ui/filePanel/filePanel.component.scss
  visualization/app/codeCharta/ui/ribbonBar/ribbonBar.component.html
  visualization/app/codeCharta/ui/ribbonBar/ribbonBar.component.scss
  visualization/app/codeCharta/ui/searchPanel/searchPanel.component.scss
Labels: UX / UI

#1930 deps: update all dependencies
  visualization/app/app.ts
  visualization/app/codeCharta/ui/areaSettingsPanel/areaSettingsPanel.po.ts
  visualization/app/codeCharta/ui/codeMap/threeViewer/threeRendererService.ts
  visualization/app/codeCharta/ui/colorSettingsPanel/colorSettingsPanel.po.ts
  visualization/app/codeCharta/ui/dialog/dialog.addCustomConfigSettings.component.ts
  visualization/app/codeCharta/ui/edgeChooser/edgeChooser.component.ts
  visualization/app/codeCharta/ui/metricDeltaSelected/metricDeltaSelected.component.ts
  visualization/app/codeCharta/ui/metricType/metricType.component.ts
  visualization/app/codeCharta/util/nodeDecorator.ts
  visualization/app/index.html
  visualization/conf/webpack.config.js
  visualization/conf/webpack.loaders.js
  visualization/package-lock.json
  visualization/package.json
Labels: dependencies, javascript

#1936 fix: husky 6 breaking changes
  .husky/.gitignore
  .husky/pre-commit
  .husky/pre-push
  package.json
Labels: dependencies
